build:
  project: '@project.artifactId@'
  timestamp: '@timestamp@'
  version: '@project.version@'

pepe:
  chapolin:
    sync_delay: ${SCHED:10000}
    stackstorm:
      url: ${STACKSTORM_URL:http://127.0.0.0:9101/v1}
      key: ${STACKSTORM_KEY:NOT_KEY}
  logging:
    tags: ${LOGGING_TAGS:default}
  event:
    ttl: ${EVENT_TTL:10000}

amqp:
  url: ${RABBIT_URL:amqp://guest:guest@127.0.0.1}
  management:
    url: ${RABBIT_MANAGEMENT_URL:http://127.0.0.1:15672/api}
    login: ${RABBIT_MANAGEMENT_LOGIN:guest}
    password: ${RABBIT_MANAGEMENT_PASSWORD:guest}

spring:
  rabbitmq:
    listener:
      type: simple
      simple:
        acknowledge-mode: manual
        prefetch: 1
  pid:
    file: ${PID_FILE:/tmp/pepe-chapolin.pid}

server:
  port: ${PORT:8000}